-- Create ifood_integration table
CREATE TABLE IF NOT EXISTS public.ifood_integration (
    id bigint generated by default as identity primary key,
    merchant_id text not null,
    client_id text not null,
    client_secret text not null, -- encrypted
    access_token text,
    token_expires_at timestamptz,
    refresh_token text,
    polling_interval integer default 30, -- seconds
    is_active boolean default false,
    last_sync_at timestamptz,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- Create ifood_product_mapping table
CREATE TABLE IF NOT EXISTS public.ifood_product_mapping (
    id bigint generated by default as identity primary key,
    ifood_product_id text not null,
    ifood_sku text,
    product_id integer not null references public.products(id) on delete cascade,
    created_at timestamptz default now(),
    unique(ifood_product_id, product_id)
);

-- Create index on ifood_sku for faster lookups
CREATE INDEX IF NOT EXISTS idx_ifood_product_mapping_sku ON public.ifood_product_mapping(ifood_sku);
CREATE INDEX IF NOT EXISTS idx_ifood_product_mapping_ifood_id ON public.ifood_product_mapping(ifood_product_id);
CREATE INDEX IF NOT EXISTS idx_ifood_product_mapping_product_id ON public.ifood_product_mapping(product_id);

-- Enable RLS
ALTER TABLE public.ifood_integration ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ifood_product_mapping ENABLE ROW LEVEL SECURITY;

-- Create policies for ifood_integration (only admins can manage)
CREATE POLICY "Enable read access for authenticated users" ON public.ifood_integration
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Enable insert for authenticated users" ON public.ifood_integration
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users" ON public.ifood_integration
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Create policies for ifood_product_mapping
CREATE POLICY "Enable read access for authenticated users" ON public.ifood_product_mapping
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Enable insert for authenticated users" ON public.ifood_product_mapping
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users" ON public.ifood_product_mapping
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Enable delete for authenticated users" ON public.ifood_product_mapping
    FOR DELETE USING (auth.role() = 'authenticated');

-- Function to update updated_at timestamp for ifood_integration
CREATE OR REPLACE FUNCTION public.update_ifood_integration_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update updated_at on ifood_integration
DROP TRIGGER IF EXISTS update_ifood_integration_updated_at_trigger ON public.ifood_integration;
CREATE TRIGGER update_ifood_integration_updated_at_trigger
    BEFORE UPDATE ON public.ifood_integration
    FOR EACH ROW EXECUTE FUNCTION public.update_ifood_integration_updated_at();

-- Force schema cache reload
NOTIFY pgrst, 'reload config';

