-- Create categories table
CREATE TABLE IF NOT EXISTS public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamptz default now()
);

-- Insert default categories
INSERT INTO public.categories (name) VALUES
    ('Burgers'),
    ('Pizza'),
    ('Drinks'),
    ('Desserts')
ON CONFLICT (name) DO NOTHING;

-- Enable RLS
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable read access for all users" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable delete for all users" ON public.categories FOR DELETE USING (true);

-- Force schema cache reload
NOTIFY pgrst, 'reload config';
